### ISSUE TITLE
Error after Instantiating LimeTabularExplainer via the Explainer interface

### ISSUE THREAD

**Issue by Rajprasath89** [SAP/contextual-ai#11]
After instantiating LimeTabularExplainer via Explainer interface, I am getting an error message:

TypeError: __init__() got an unexpected keyword argument 'sample_around_instance'

I guess this should be because of latest release. I dont see this error message on previous versions. Suggestions please?

**Comment by seansaito** [comment]
Hi Rajprasath, thanks for raising the issue. Do you mean that this error happens for later versions of LIME?

**Comment by postalC** [comment]
@Rajprasath89 can you share some sample code or notebook, how to reproduce the issue and using what data set? thanks

**Comment by wangjin1024** [comment]
@Rajprasath89 Could you provide the version of the library that you are using and some sample codes? It may be due to a misalignment on the library version. "sample_around_instance" is a new attribute introduced in the latest version of lime.

**Comment by wangjin1024** [comment]
@Rajprasath89 I will close this issue for now as we haven't heard from you for long, please let me know if you need more help for debugging. Thanks.
