### ISSUE TITLE
Query - Is contextual-ai library shap and lime tested on GPU environment ? 

### ISSUE THREAD

**Issue by manduripramodh** [SAP/contextual-ai#13]
Hi , 

Is contextual-ai library shap and lime tested on GPU environment ?  If yes, adding more GPU's will it improve the performance

**Comment by wangjin1024** [comment]
Hi @manduripramodh, for now the shap and lime are mainly ran on CPU only as the library doesn't provide GPU implementation yet. Feel free to folk and contribute a GPU implementation or any parallel-based implementation to boost the performance.
